-- ##### Création de la table des Communes #####
CREATE TABLE commune (
    id_commune NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique de la commune
    nom VARCHAR2(100) NOT NULL UNIQUE                           -- Nom unique de la commune
);

-- ##### Création de la table des Arrondissements #####
CREATE TABLE arrondissement (
    id_arrondissement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique de l'arrondissement
    id_commune NUMBER NOT NULL,                                           -- Référence vers la commune
    nom VARCHAR2(100) NOT NULL,                                          -- Nom de l'arrondissement
    FOREIGN KEY (id_commune) REFERENCES commune(id_commune)              -- Clé étrangère vers la table des communes
);

-- ##### Création de la table des Polygones #####
CREATE TABLE polygone (
    id_polygone NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du polygone
    id_arrondissement NUMBER NOT NULL,                               -- Référence vers l'arrondissement
    longitude NUMBER(10, 6) NOT NULL,                               -- Coordonnée longitude
    latitude NUMBER(10, 6) NOT NULL,                                -- Coordonnée latitude
    FOREIGN KEY (id_arrondissement) REFERENCES arrondissement(id_arrondissement) -- Clé étrangère vers la table des arrondissements
);

-- ##### Création de la table des prix d'impôts par m² #####
CREATE TABLE prix_impot (
    id_prix NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du prix d'impôt
    id_commune NUMBER NOT NULL,                                  -- Référence vers la commune
    valeur NUMBER(10, 2) NOT NULL,                              -- Valeur du prix par m²
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,            -- Dernière mise à jour
    FOREIGN KEY (id_commune) REFERENCES commune(id_commune)     -- Clé étrangère vers la table des communes
);

-- ##### Création de la table des bâtiments (Trano) #####
CREATE TABLE maison (
    id_trano NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du bâtiment
    id_proprietaire NUMBER NOT NULL,                              -- Identifiant du propriétaire
    nom VARCHAR2(100) NOT NULL,                                  -- Nom du bâtiment
    longitude NUMBER(10, 6) NOT NULL,                            -- Coordonnée longitude
    latitude NUMBER(10, 6) NOT NULL                              -- Coordonnée latitude
);

-- ##### Création de la table des surfaces des bâtiments #####
CREATE TABLE maison_detaills (
    id_trano NUMBER NOT NULL,                                     
    longueur NUMBER(10, 2) NOT NULL,                             
    largeur NUMBER(10, 2) NOT NULL,                              
    nb_etages NUMBER NOT NULL, 
    id_type_tafo NUMBER NOT NULL,
    id_type_rindrina NUMBER NOT NULL,                                                                       -- Date de fin de validité (optionnelle)
    PRIMARY KEY (id_trano),                          
    FOREIGN KEY (id_trano) REFERENCES trano(id_trano),
    FOREIGN KEY (id_type_tafo) REFERENCES type_tafo(id_type_tafo),
    FOREIGN KEY (id_type_rindrina) REFERENCES type_rindrina(id_type_rindrina)
);

CREATE TABLE type_tafo(
    id_type_tafo,
    nom
)

create table type_tafo_coefficient(
    id_type_tafo,
    coefficient,
    date
);

CREATE table type_rindrina(
    id_type_rindrina
    nom
)

create table type_rindrina_coefficient(
    id_type_rindrina,
    coefficient,
    date
);