-- ##### Création de la table des Communes #####
CREATE TABLE commune (
    id_commune NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique de la commune
    nom VARCHAR2(100) NOT NULL UNIQUE                           -- Nom unique de la commune
);

-- ##### Création de la table des Arrondissements #####
CREATE TABLE arrondissement (
    id_arrondissement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique de l'arrondissement
    id_commune NUMBER NOT NULL,                                           -- Référence vers la commune
    nom VARCHAR2(100) NOT NULL,                                          -- Nom de l'arrondissement
    FOREIGN KEY (id_commune) REFERENCES commune(id_commune)              -- Clé étrangère vers la table des communes
);

-- ##### Création de la table des Polygones #####
CREATE TABLE polygone (
    id_polygone NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du polygone
    id_arrondissement NUMBER NOT NULL,                               -- Référence vers l'arrondissement
    longitude NUMBER(10, 6) NOT NULL,                               -- Coordonnée longitude
    latitude NUMBER(10, 6) NOT NULL,                                -- Coordonnée latitude
    FOREIGN KEY (id_arrondissement) REFERENCES arrondissement(id_arrondissement) -- Clé étrangère vers la table des arrondissements
);
-- ##### Création de la table des prix d'impôts par m² #####
CREATE TABLE prix_impot (
    id_prix NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du prix d'impôt
    id_commune NUMBER NOT NULL,                                  -- Référence vers la commune
    valeur NUMBER(10, 2) NOT NULL,                              -- Valeur du prix par m²
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,            -- Dernière mise à jour
    FOREIGN KEY (id_commune) REFERENCES commune(id_commune)     -- Clé étrangère vers la table des communes
);

-- ##### Création de la table des bâtiments (Trano) #####
CREATE TABLE trano (
    id_trano NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du bâtiment
    id_proprietaire NUMBER NOT NULL,                              -- Identifiant du propriétaire
    nom VARCHAR2(100) NOT NULL,                                  -- Nom du bâtiment
    longitude NUMBER(10, 6) NOT NULL,                            -- Coordonnée longitude
    latitude NUMBER(10, 6) NOT NULL                              -- Coordonnée latitude
);



-- ##### Création de la table des surfaces des bâtiments #####
CREATE TABLE trano_surface (
    id_trano NUMBER NOT NULL,                                     -- Référence vers le bâtiment
    longueur NUMBER(10, 2) NOT NULL,                             -- Longueur du bâtiment
    largeur NUMBER(10, 2) NOT NULL,                              -- Largeur du bâtiment
    nb_etages NUMBER NOT NULL,                                   -- Nombre d'étages
    date_debut DATE NOT NULL,                                    -- Date de début de validité
    date_fin DATE,                                               -- Date de fin de validité (optionnelle)
    PRIMARY KEY (id_trano, date_debut),                          -- Clé primaire composite
    FOREIGN KEY (id_trano) REFERENCES trano(id_trano)            -- Clé étrangère vers la table des bâtiments
);

-- ##### Création de la table des catégories de caractéristiques #####
CREATE TABLE categorie_caracteristique (
    id_categorie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique de la catégorie
    nom VARCHAR2(50) UNIQUE NOT NULL                                   -- Nom unique de la catégorie
);

-- ##### Création de la table des caractéristiques #####
CREATE TABLE caracteristique (
    id_caracteristique NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique de la caractéristique
    id_categorie NUMBER NOT NULL,                                           -- Référence vers la catégorie
    materiau VARCHAR2(50) NOT NULL,                                         -- Matériau de la caractéristique
    FOREIGN KEY (id_categorie) REFERENCES categorie_caracteristique(id_categorie) -- Clé étrangère vers la table des catégories
);

-- ##### Création de la table des coefficients des caractéristiques par commune #####
CREATE TABLE coeff_caracteristique (
    id_coeff NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identifiant unique du coefficient
    id_caracteristique NUMBER NOT NULL,                          -- Référence vers la caractéristique
    id_commune NUMBER NOT NULL,                                  -- Référence vers la commune
    coeff_valeur NUMBER(10, 2) NOT NULL,                        -- Valeur du coefficient
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,            -- Dernière mise à jour
    FOREIGN KEY (id_caracteristique) REFERENCES caracteristique(id_caracteristique), -- Clé étrangère vers la table des caractéristiques
    FOREIGN KEY (id_commune) REFERENCES commune(id_commune)     -- Clé étrangère vers la table des communes
);

-- ##### Création de la table de liaison bâtiment-caractéristique #####
CREATE TABLE trano_caracteristique (
    id_trano NUMBER NOT NULL,                                -- Référence vers le bâtiment
    id_caracteristique NUMBER NOT NULL,                     -- Référence vers la caractéristique
    date_debut DATE NOT NULL,                               -- Date de début de validité
    date_fin DATE,                                          -- Date de fin de validité (optionnelle)
    PRIMARY KEY (id_trano, id_caracteristique, date_debut), -- Clé primaire composite
    FOREIGN KEY (id_trano) REFERENCES trano(id_trano),      -- Clé étrangère vers la table des bâtiments
    FOREIGN KEY (id_caracteristique) REFERENCES caracteristique(id_caracteristique) -- Clé étrangère vers la table des caractéristiques
);