CREATE VIEW PREVISION_COMPLET_CPL_DEP AS SELECT * FROM PREVISION_COMPLET_CPL pcc  WHERE 
debit > 0;

CREATE VIEW PREVISION_COMPLET_CPL_REC AS SELECT * FROM PREVISION_COMPLET_CPL pcc  WHERE 
credit > 0;
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0020004', 'prevision dépense', 'fa fa-tags', '#', 4, 2, 'MENUDYN002');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0020005', 'prevision recette', 'fa fa-tags', '#', 5, 2, 'MENUDYN002');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0020006', 'Saisie', 'fa fa-plus', 'module.jsp?but=prevision/prevision-liste-depense-echue.jsp', 1, 3, 'MENUDYN0020004');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0020008', 'Saisie', 'fa fa-plus', 'module.jsp?but=prevision/prevision-liste-recette-echue.jsp', 1, 3, 'MENUDYN0020005');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0020007', 'Liste', 'fa fa-list', 'module.jsp?but=prevision/prevision-liste-depense.jsp', 2, 3, 'MENUDYN0020004');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0020009', 'Liste', 'fa fa-list', 'module.jsp?but=prevision/prevision-liste-recette.jsp', 2, 3, 'MENUDYN0020005');

CREATE VIEW Prevision_COMPLET_CPL_NR AS SELECT * FROM 
PREVISION_COMPLET_CPL_DEP
where depenseEcart > 0
UNION ALL 
 SELECT * FROM
PREVISION_COMPLET_CPL_REC
where recetteEcart > 0;