INSERT INTO FOURNISSEUR
(ID, NOM, NIF, STAT, ADRESSE, CONTACT, CODEPOSTAL, COMPTE)
VALUES('FRNDIV01', 'Divers Fournisseur', NULL, NULL, NULL, NULL, NULL, '401001');

INSERT INTO CLIENT
(ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE)
VALUES('CLI000054', 'divers', '03433525', 'divers@gmail.com', 'Ampefiloha', 'Andraharo', '411012');
